### PR TITLE
Add exception handling for login

### LINKED ISSUE #6: Login Page (Evan)

### PR DESCRIPTION
**Pull request by EvanMateo7**
All tasks completed for issue 6.
Closes #6

### CODE REVIEW

**Comment by EvanMateo7** [comment]
Needs peer testing before merge

**Comment by LHuss** [comment]
You should add password strength while you're at it, as requested (issue #not yet available)

**Comment by LHuss** [comment]
Is there a reason you removed the logout text when clicking log out button? Other than that everything looks good.

**Comment by EvanMateo7** [comment]
The softkeyboard blocks it. I just made it more convenient for now. The layout will be improved later on.

**Pull request merged**
