### PR TITLE
Feature/s3item information

### PR DESCRIPTION
**Pull request by LHuss**
What was added:
-An xml to reflect the item's information
-A fragment to show the item information
-A method in MainActivity to switch to that fragment (called onClick of a view in the item listing xml)
-An item description class to store the item information
-A helper class. In it, a nullorempty method for strings. Was tired of doing that repeatedly

Note: may need UI polishing, because I suck at UI.

This covers issue #29

### CODE REVIEW

**Comment by EvanMateo7** [comment]
The app crashes when I select the potato item only. I can't figure out why. Can you check this?

**Comment by LHuss** [comment]
@melodyvibe Couldn't reproduce the crash. However, I did notice that the ImageURL was labeled ImageUrl in the database (Lowercase rl in URL), so that may have been the cause.

**Comment by EvanMateo7** [comment]
Yup. Looks like its working now. Good find @LHuss

**Review by EvanMateo7 — APPROVED** [review]

**Comment by LHuss** [comment]
Review accepted. Close #29

**Pull request merged**
