### PR TITLE
Removed ignored .idea/ files.

### PR DESCRIPTION
**Pull request by kwreen**
Files that should've been off the remote repo were still on it. I removed them.

### CODE REVIEW

**Comment by kwreen** [comment]
Second pull request because I needed to modify something, but I recloned the repo due to build issues and  couldn't anymore.

**Comment by LHuss** [comment]
What did you change in the gradlew file? Your commit message doesn't mention that you touched it at all, but I see basically the whole file has changed

**Comment by kwreen** [comment]
@LHuss There are no modifications in the gradlew file, I think it might be showing the changes because I removed the thing and added it back? Not sure, but comparing the two shows that they're identical, unless I missed something?

**Comment by LHuss** [comment]
@kwreen ah okay. In the future, try not to commit files unless they're relevant to the rest of the commit  please :)

**Comment by kwreen** [comment]
@LHuss You're right. I just didn't want to bother with it since there were no actual modifications, but you're correct in the fact that they were irrelevant to my commit. I just fixed it.

**Comment by LHuss** [comment]
Merging now because it is a small change, and will block many future pull requests.

**Pull request merged**
